### ISSUE TITLE
Auto-renaming the old forum pages URLs

### ISSUE THREAD

**Issue by HLFH** [Avatar4eg/flarum-ext-transliterator#1]
Hi,
1. I installed your extension.
2. I enabled your extension in the admin settings
3. I have created before a private forum page and I launched again this forum page: https://forum.acsemb.org/d/1-r-glement-du-forum-priv and sadly, it seems the URL is staying like that. The title is: **Règlement du forum privé**. So the URL transliteration does not work apparently. IMHO, the URL should be https://forum.acsemb.org/d/1-reglement-du-forum-prive, I believe.
4. Btw, I'm using Flarum 0.1.0-beta.5.

Do you have any idea how to fix this?

**Comment by HLFH** [comment]
Edit: it works but you have to fix manually the pages URLs by renaming them twice, then the `flarum-ext-transliterator` extension does its job.
![capture d ecran 2016-09-22 a 14 24 04](https://cloud.githubusercontent.com/assets/2359059/18747949/4580a34e-80d0-11e6-9289-0f3b9d0a4ecb.png)

Could we do it less manually for the old forum pages URLs?

**Comment by Avatar4eg** [comment]
Fixed in [0.4.0](https://github.com/Avatar4eg/flarum-ext-transliterator/releases/tag/0.4.0) (added button to rebuild slugs).

**Comment by HLFH** [comment]
Thank you!
